# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcfee75da4f3aef18bdfc674c2dfa836300d6409b1b5ec44232b62ca6e5767686d41095e2a200c96f47fe8c41d7c240c2a8cae8936ef4a53dd6c7f93e4c9b55a

test:
  secret_key_base: 38c66cf11aecbb3a80fdc1ef5c5e6a8765804ea3241052323ab6a7bb1dc051d18b8572a726e5ad15de33a63682107d51bff134ace7eca7fc24dfe28a3d006559

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
